import { Property } from './types';

export const INITIAL_PROPERTIES: Omit<Property, 'id' | 'created_at'>[] = [
  {
    title: "Premium 3 BHK G+1 Individual House in Venkat Nagar",
    location: "Venkat Nagar",
    type: "Individual House",
    listing_type: "Buy",
    price: 8500000,
    rent: 0,
    description: "Premium double-floor G+1 independent house with flat roof design, steel railings, and sweet municipal water connection in elite Venkat Nagar layout. Fully vaastu-compliant.",
    image_url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=80",
    owner_name: "Dr. Srinivas Rao",
    phone: "+919177589321",
    sqft: 2200,
    bedrooms: 3,
    bathrooms: 3,
    building_age: 3,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Cozy 1 BHK Ground Floor Small House in Gandhinagar",
    location: "Gandhinagar",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 8500,
    description: "Charming independent ground floor house with a small front veranda in Gandhinagar. Prime center, walk to local market. 24 hours borewell and separate electricity sub-meter.",
    image_url: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?auto=format&fit=crop&w=800&q=80",
    owner_name: "M. Venkata Ramana",
    phone: "+919440156789",
    sqft: 650,
    bedrooms: 1,
    bathrooms: 1,
    building_age: 6,
    water_supply: "Borewell",
    parking: false
  },
  {
    title: "Modern 3 BHK Flat near Beach Road (Seafacing View)",
    location: "Beach Road",
    type: "Apartment",
    listing_type: "Buy",
    price: 6800000,
    rent: 0,
    description: "Sea-breeze facing modern apartment on Beach Road. Dual luxury balconies, spacious modular kitchen, lift facility, power backup and dedicated car garage.",
    image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    owner_name: "K. Raghupathi Raju",
    phone: "+919848012345",
    sqft: 1650,
    bedrooms: 3,
    bathrooms: 3,
    building_age: 2,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Convenient 2 BHK Flat near Bhanugudi Junction",
    location: "Bhanugudi Junction",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 14000,
    description: "Highly accessible 2nd floor flat near Bhanugudi Junction. Adjacent to leading corporate hospitals, stores, and main schools. Has continuous sweet municipal water pipelines.",
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    owner_name: "Ch. Lakshmi Narayana",
    phone: "+917702456123",
    sqft: 1150,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 4,
    water_supply: "Municipal",
    parking: true
  },
  {
    title: "Budget-Friendly Independent Small House at Indrapalem",
    location: "Indrapalem",
    type: "Small House",
    listing_type: "Buy",
    price: 2400000,
    rent: 0,
    description: "Single floor concrete independent home with secure iron boundary gates. Located in quiet, sweet groundwater zone of Indrapalem. Selling urgently due to family relocation.",
    image_url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
    owner_name: "G. Satyanarayana",
    phone: "+919000123987",
    sqft: 800,
    bedrooms: 2,
    bathrooms: 1,
    building_age: 8,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Spacious 2 BHK Ground Floor House in Sarpavaram",
    location: "Sarpavaram",
    type: "Individual House",
    listing_type: "Rent",
    price: 0,
    rent: 11000,
    description: "Independent ground floor layout near Sarpavaram Junction. Highly ventilated, modern styling, with spacious car parking. Sweet drinking water tap available.",
    image_url: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80",
    owner_name: "P. Satya Murthy",
    phone: "+918885612344",
    sqft: 1200,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 5,
    water_supply: "Municipal",
    parking: true
  },
  {
    title: "Luxurious 4 BHK Duplex House in Suryaraopeta",
    location: "Suryaraopeta",
    type: "Individual House",
    listing_type: "Buy",
    price: 9500000,
    rent: 0,
    description: "Pristine duplex independent villa with elegant elevation, spacious balconies, and premium Italian modular kitchen. Right in central premium Suryaraopeta near main hospitals.",
    image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    owner_name: "V. Subba Raju",
    phone: "+919010456789",
    sqft: 2800,
    bedrooms: 4,
    bathrooms: 4,
    building_age: 1,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Convenient 1 BHK Row House near Jagannaickpur",
    location: "Jagannaickpur",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 6500,
    description: "Compact single bedroom house with a private puja room and wash area near Jagannaickpur Bridge. Safe neighborhood, very walking distance to local markets.",
    image_url: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    owner_name: "K. Mohan Rao",
    phone: "+919490123344",
    sqft: 580,
    bedrooms: 1,
    bathrooms: 1,
    building_age: 10,
    water_supply: "Borewell",
    parking: false
  },
  {
    title: "Modern 2 BHK Flat in Balaji Cheruvu",
    location: "Balaji Cheruvu",
    type: "Apartment",
    listing_type: "Buy",
    price: 4200000,
    rent: 0,
    description: "Just 2 years old modern apartment building in Balaji Cheruvu. Highly desired by bachelors/professors due to proximity to JNTUK. Features generator backup and lift facilities.",
    image_url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
    owner_name: "A. Srikanth",
    phone: "+917382012948",
    sqft: 1050,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 2,
    water_supply: "Municipal",
    parking: true
  },
  {
    title: "Comfortable 2 BHK Apartment in Dairy Farm Center",
    location: "Dairy Farm Center",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 9500,
    description: "Gated concrete building flat in Dairy Farm Center. Wide roads, extremely calm residential street. Has individual electric meter and sweet drinking water connection.",
    image_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    owner_name: "S. Nageswara Rao",
    phone: "+919100456123",
    sqft: 1100,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 5,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Independent G+1 3 BHK House at Ramanaiahpeta",
    location: "Ramanayyapeta",
    type: "Individual House",
    listing_type: "Buy",
    price: 7800000,
    rent: 0,
    description: "Exquisite individual G+1 house with sturdy foundation, compound wall gates, and spacious bike/car porches in Ramanayyapeta. Near top diagnostics and schools.",
    image_url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
    owner_name: "T. Venkat Reddy",
    phone: "+919494123456",
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 3,
    building_age: 4,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Affordable 1 BHK Ground Room House in Turangi",
    location: "Turangi",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 5000,
    description: "Extremely affordable independent house in peaceful Turangi area. Suitable for small family or port workers. Includes separate water connection.",
    image_url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    owner_name: "D. Gangadhar",
    phone: "+919866123412",
    sqft: 500,
    bedrooms: 1,
    bathrooms: 1,
    building_age: 9,
    water_supply: "Borewell",
    parking: false
  },
  {
    title: "Premium 3 BHK Villa in Rama Nivas Layout (Sarpavaram)",
    location: "Sarpavaram",
    type: "Individual House",
    listing_type: "Buy",
    price: 9000000,
    rent: 0,
    description: "Newly built modern 3 BHK villa with high ceilings, vitrified tiles, designer elevation, and private terrace in Sarpavaram. Close to local outer ring bypass road.",
    image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
    owner_name: "Ch. Ramakrishna",
    phone: "+919951123456",
    sqft: 2400,
    bedrooms: 3,
    bathrooms: 3,
    building_age: 1,
    water_supply: "Both",
    parking: true
  },
  {
    title: "2 BHK Premium Flat for Rent near APSP Area",
    location: "APSP Area",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 12000,
    description: "Beautiful 2 BHK configuration flat in highly secure APSP Area. Offers covered car parking, lift, separate utilities, and round-the-clock watchman security.",
    image_url: "https://images.unsplash.com/photo-1448630360428-654a95bfee3e?auto=format&fit=crop&w=800&q=80",
    owner_name: "K. Prasad",
    phone: "+919440234567",
    sqft: 1250,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 3,
    water_supply: "Municipal",
    parking: true
  },
  {
    title: "Solid Ground Floor House (Future G+1 support) at Indrapalem",
    location: "Indrapalem",
    type: "Individual House",
    listing_type: "Buy",
    price: 4900000,
    rent: 0,
    description: "Solid construction with superior Vizag-steel columns designed to easily build first/second floors. Clear title with approved blueprints and LRS fully cleared.",
    image_url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80",
    owner_name: "B. Veerraju",
    phone: "+919885123123",
    sqft: 1400,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 4,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Charming independent room in Sambamurthy Nagar",
    location: "Sambamurthy Nagar",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 7500,
    description: "1 BHK independent house located in a clean street. Sweet drinking municipal water tap, close to parks, super-specialty hospitals, and markets. Family preferred.",
    image_url: "https://images.unsplash.com/photo-1598257006458-087169a1f08d?auto=format&fit=crop&w=800&q=80",
    owner_name: "L. Appa Rao",
    phone: "+918008123456",
    sqft: 600,
    bedrooms: 1,
    bathrooms: 1,
    building_age: 7,
    water_supply: "Municipal",
    parking: true
  },
  {
    title: "Independent Beachfront G+1 House (Thimmapuram)",
    location: "Thimmapuram",
    type: "Individual House",
    listing_type: "Buy",
    price: 7200000,
    rent: 0,
    description: "Excellent G+1 construct in highly growing Thimmapuram, close to coastal beach road resorts. Superior plastering, safe ground water, and gorgeous sea winds.",
    image_url: "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?auto=format&fit=crop&w=800&q=80",
    owner_name: "N. Jagan Mohan Rao",
    phone: "+919440456122",
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 3,
    building_age: 3,
    water_supply: "Both",
    parking: true
  },
  {
    title: "1 BHK Budget Employee Flat in Vakalapudi Area",
    location: "Vakalapudi",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 6000,
    description: "Cozy flat highly suited for local port workers or industrial employees. Quick reach to Vakalapudi beach highway. Reasonable rent includes direct building maintenance.",
    image_url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    owner_name: "P. Ranga Rao",
    phone: "+919849123456",
    sqft: 550,
    bedrooms: 1,
    bathrooms: 1,
    building_age: 5,
    water_supply: "Borewell",
    parking: true
  },
  {
    title: "4 BHK Premium Luxury Villa in Madhavapatnam Colony",
    location: "Madhavapatnam",
    type: "Individual House",
    listing_type: "Buy",
    price: 9800000,
    rent: 0,
    description: "Ultra premium 4 BHK individual building on large plots in Madhavapatnam. High brick boundary walls, modular puja room, car porch with marble pathways. Serene location.",
    image_url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
    owner_name: "M. Somaraju",
    phone: "+919502123456",
    sqft: 3200,
    bedrooms: 4,
    bathrooms: 4,
    building_age: 1,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Spacious 2 BHK Ground Floor Port Area House",
    location: "Port Area",
    type: "Individual House",
    listing_type: "Rent",
    price: 0,
    rent: 10000,
    description: "Spacious independent ground block in Port Area. 2 bed rooms, very wide dining block, separate utility. Secure with full iron windows and secure gate.",
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
    owner_name: "T. Durga Prasad",
    phone: "+918123456789",
    sqft: 1300,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 6,
    water_supply: "Municipal",
    parking: true
  },
  {
    title: "Affordable 1 BHK House in Narasannapeta Suburbs",
    location: "Narasannapeta",
    type: "Small House",
    listing_type: "Buy",
    price: 1800000,
    rent: 0,
    description: "Extremely affordable independent brick home with steel roofing. Fully approved local layout blueprint with sweet groundwater. Perfect starter home.",
    image_url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    owner_name: "G. Apparao Chowdary",
    phone: "+919440123567",
    sqft: 450,
    bedrooms: 1,
    bathrooms: 1,
    building_age: 10,
    water_supply: "Borewell",
    parking: false
  },
  {
    title: "1 BHK Studio Small House for Rent (Vakalapudi)",
    location: "Vakalapudi",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 4200,
    description: "Affordable single room studio cottage with private bathroom and kitchen shelf. Clean family environment, secure borewell connection. Immediate occupancy.",
    image_url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    owner_name: "Y. Rama Rao",
    phone: "+919618123456",
    sqft: 400,
    bedrooms: 1,
    bathrooms: 1,
    building_age: 8,
    water_supply: "Borewell",
    parking: false
  },
  {
    title: "Prime 3 BHK Builder Flat in center Gandhinagar",
    location: "Gandhinagar",
    type: "Apartment",
    listing_type: "Buy",
    price: 7500000,
    rent: 0,
    description: "Premium model custom flat block in prime residential Gandhinagar colony. Close to main temples, bus stands, and schools. 24 hours watchman, parking, and municipal line.",
    image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    owner_name: "B. Satya Murthy Raju",
    phone: "+919866456781",
    sqft: 1800,
    bedrooms: 3,
    bathrooms: 3,
    building_age: 3,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Spacious 3 BHK Flat in premium Venkat Nagar",
    location: "Venkat Nagar",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 22000,
    description: "Premium high-grade 3 BHK flat. Teak woodwork, spacious bathrooms, modular electrical systems, and dedicated parking. Corporate officers or doctor families highly preferred.",
    image_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    owner_name: "Dr. K. S. Reddy",
    phone: "+919441122334",
    sqft: 2100,
    bedrooms: 3,
    bathrooms: 3,
    building_age: 2,
    water_supply: "Both",
    parking: true
  },
  {
    title: "Budget 2 BHK House direct on Peddapuram Road",
    location: "Peddapuram Road",
    type: "Individual House",
    listing_type: "Buy",
    price: 3800000,
    rent: 0,
    description: "Direct on Peddapuram road near Aditya engineering colleges. Perfect layout investment opportunity with high demand student renting yields. Independent borewell water.",
    image_url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
    owner_name: "Ch. Venkata Rao",
    phone: "+918978123456",
    sqft: 1350,
    bedrooms: 2,
    bathrooms: 2,
    building_age: 5,
    water_supply: "Borewell",
    parking: true
  }
];
