import { Property } from './types';

export const INITIAL_PROPERTIES: Omit<Property, 'id' | 'created_at'>[] = [
  {
    title: "Scenic 3 BHK Apartment near Beach Road",
    location: "Beach Road",
    type: "Apartment",
    listing_type: "Buy",
    price: 6800000,
    rent: 0,
    description: "Beautiful sea-facing apartment on Beach Road. Located on the 4th floor with dual balconies offering spectacular ocean breezes. Includes designated car parking and 24/7 security. Setting price slightly lower for a quick sale.",
    image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    owner_name: "K. Raghupathi Raju",
    phone: "+919848012345"
  },
  {
    title: "Cozy Small House in Gandhinagar",
    location: "Gandhinagar",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 8500,
    description: "Perfect single-bedroom independent house with a small front yard in Gandhinagar. Prime center location, very walking distance to supermarkets and local temples. Rent includes water charge. Suited for couples or bachelors.",
    image_url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    owner_name: "M. Venkata Ramana",
    phone: "+919440156789"
  },
  {
    title: "Premium 3 BHK Individual House in Venkat Nagar",
    location: "Venkat Nagar",
    type: "Individual House",
    listing_type: "Buy",
    price: 8500000,
    rent: 0,
    description: "G+1 fully independent house in the prestige lay-out of Venkat Nagar. Ground floor has 2 spacious bedrooms, first floor has 1 bedroom plus open terrace. Beautiful landscaping, teak wood doors, and municipal sweet water line.",
    image_url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    owner_name: "Dr. Srinivas Rao",
    phone: "+919177589321"
  },
  {
    title: "Comfortable 2 BHK Apartment for Rent in Bhanugudi Junction",
    location: "Bhanugudi Junction",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 14000,
    description: "Highly accessible 2 BHK flat near Bhanugudi Junction. Located adjacent to several corporate hospitals, multi-brand stores, and top schools. Has municipal water supply, lift facility, and round the clock watchman.",
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    owner_name: "Ch. Lakshmi Narayana",
    phone: "+917702456123"
  },
  {
    title: "Budget-Friendly Small House in Indrapalem",
    location: "Indrapalem",
    type: "Small House",
    listing_type: "Buy",
    price: 2400000,
    rent: 0,
    description: "Independent single-floor small house in Indrapalem. Safe residential area with very sweet groundwater connection. Highly affordable budget price due to urgent family relocation. Ideal first home for small families.",
    image_url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    owner_name: "G. Satyanarayana",
    phone: "+919000123987"
  },
  {
    title: "Spacious 2 BHK Individual House in Sarpavaram",
    location: "Sarpavaram",
    type: "Individual House",
    listing_type: "Rent",
    price: 0,
    rent: 11000,
    description: "Beautiful independent 2 BHK ground floor house in Sarpavaram, very close to JNTU Kakinada road. Fully vaastu-compliant, well-ventilated, car parking space available. Looking for decent family/salaried tenants.",
    image_url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    owner_name: "P. Satya Murthy",
    phone: "+918885612344"
  },
  {
    title: "Luxurious duplex 4 BHK House in Suryaraopeta",
    location: "Suryaraopeta",
    type: "Individual House",
    listing_type: "Buy",
    price: 9500000,
    rent: 0,
    description: "Fabulous double-story duplex villa in the heart of Suryaraopeta. Extremely premium construction with high-end marbles and Italian modular kitchen. Close to prime government hospitals, luxury hotels, and main markets.",
    image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    owner_name: "V. Subba Raju",
    phone: "+919010456789"
  },
  {
    title: "Charming 1 BHK Row House near Jagannaickpur",
    location: "Jagannaickpur",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 6500,
    description: "Compact independent 1 BHK house near Jagannaickpur Bridge. Features a separate puja mandiram and utility area. Highly convenient for port workers or local market shop owners. Very reasonable rent.",
    image_url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    owner_name: "K. Mohan Rao",
    phone: "+919490123344"
  },
  {
    title: "Modern 2 BHK Flat in Balaji Cheruvu",
    location: "Balaji Cheruvu",
    type: "Apartment",
    listing_type: "Buy",
    price: 4200000,
    rent: 0,
    description: "Constructed recently (just 2 years old) 2 BHK flat in Balaji Cheruvu. High-quality construction, close to educational institutes like JNTUK, Aditya, and Pragati. Lift facility, power backup, and security guard included.",
    image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    owner_name: "A. Srikanth",
    phone: "+917382012948"
  },
  {
    title: "Cozy 2 BHK Flat near Dairy Farm Center",
    location: "Dairy Farm Center",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 9500,
    description: "Fully styled 2 BHK apartment for rent in Dairy Farm Center. Situated in a clean, quiet street yet minutes away from the main commercial road. 24-hours borewell water and municipal water lines. Easy commute to central Kakinada.",
    image_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    owner_name: "S. Nageswara Rao",
    phone: "+919100456123"
  },
  {
    title: "Spacious Duplex House in Ramanaiahpeta",
    location: "Ramanayyapeta",
    type: "Individual House",
    listing_type: "Buy",
    price: 7800000,
    rent: 0,
    description: "Classic design 3 BHK duplex home situated in Ramanayyapeta close to banks and super-specialty hospitals. Ground floor contains living hall and a master bed; first floor features 2 bedrooms and study. Includes private car garage.",
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
    owner_name: "T. Venkat Reddy",
    phone: "+919494123456"
  },
  {
    title: "Affordable 1 BHK House in Turangi",
    location: "Turangi",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 5000,
    description: "Decent independent 1 BHK small house in peaceful Turangi area. Highly affordable rent, perfect for newly married couples or working individuals. Very sweet drinking water and separate power sub-meter.",
    image_url: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    owner_name: "D. Gangadhar",
    phone: "+919866123412"
  },
  {
    title: "Pristine 3 BHK Premium Villa in Sarpavaram",
    location: "Sarpavaram",
    type: "Individual House",
    listing_type: "Buy",
    price: 9000000,
    rent: 0,
    description: "Newly built modern 3 BHK villa in Ramanivas gated layout, Sarpavaram. Extremely close to Outer Ring Road and JNTUK campus. High ceilings, vitrified tiles, designer bath fittings, and parking space for 2 SUVs.",
    image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
    owner_name: "Ch. Ramakrishna",
    phone: "+919951123456"
  },
  {
    title: "2 BHK Flat with Great Amenities in APSP Area",
    location: "APSP Area",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 12000,
    description: "Modern 2 BHK flat on the 2nd line of APSP Area. Offers covered bike & car parking, private lift, and gated security. Safe atmosphere, walking distance to police parade grounds and main highway bus stops.",
    image_url: "https://images.unsplash.com/photo-1448630360428-654a95bfee3e?auto=format&fit=crop&w=800&q=80",
    owner_name: "K. Prasad",
    phone: "+919440234567"
  },
  {
    title: "Individual Ground Floor House in Indrapalem",
    location: "Indrapalem",
    type: "Individual House",
    listing_type: "Buy",
    price: 4900000,
    rent: 0,
    description: "2 BHK independent house on 180 sq. yards site at Indrapalem. Features sturdy columns built with superior steel, designed for future second-floor construction. Clear title with verified plans and LRS cleared.",
    image_url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
    owner_name: "B. Veerraju",
    phone: "+919885123123"
  },
  {
    title: "Small House near Sambamurthy Nagar",
    location: "Sambamurthy Nagar",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 7500,
    description: "1 BHK independent house situated in a peaceful neighborhood of Sambamurthy Nagar. Highly convenient location with parks and local markets nearby. Suitable for long-term lease or rental agreements.",
    image_url: "https://images.unsplash.com/photo-1598257006458-087169a1f08d?auto=format&fit=crop&w=800&q=80",
    owner_name: "L. Appa Rao",
    phone: "+918008123456"
  },
  {
    title: "Independent house on Thimmapuram Beach Rd",
    location: "Thimmapuram",
    type: "Individual House",
    listing_type: "Buy",
    price: 7200000,
    rent: 0,
    description: "G+1 construction 3 BHK house at Thimmapuram, close to beach road resorts. Built recently with exquisite standard materials, perfect ground water, and sweet breeze. Selling owing to settlement abroad.",
    image_url: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80",
    owner_name: "N. Jagan Mohan Rao",
    phone: "+919440456122"
  },
  {
    title: "1 BHK Apartment for Rent in Vakalapudi",
    location: "Vakalapudi",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 6000,
    description: "Cozy 1 BHK flat perfect for industrial employees working near the port or Vakalapudi industrial area. Easy access to local beach road and highway bus connectivity. Rent includes maintenance.",
    image_url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    owner_name: "P. Ranga Rao",
    phone: "+919849123456"
  },
  {
    title: "Huge 4 BHK Luxury Villa in Madhavapatnam",
    location: "Madhavapatnam",
    type: "Individual House",
    listing_type: "Buy",
    price: 9800000,
    rent: 0,
    description: "Luxury premium 4 BHK individual house built on 300 square yards at Madhavapatnam. High security compound, modular puja mandir, double car porch, state-of-the-art marble elevations. Highly residential serene colony.",
    image_url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    owner_name: "M. Somaraju",
    phone: "+919502123456"
  },
  {
    title: "Cozy 2 BHK House in Port Area",
    location: "Port Area",
    type: "Individual House",
    listing_type: "Rent",
    price: 0,
    rent: 10000,
    description: "Ground floor of a spacious individual house in Port Area. 2 bed rooms, spacious hall, separate kitchen layout. Fully secure iron grills, sweet drinking water and parking available for two wheelers and small car.",
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
    owner_name: "T. Durga Prasad",
    phone: "+918123456789"
  },
  {
    title: "Budget House in Narasannapeta",
    location: "Narasannapeta",
    type: "Small House",
    listing_type: "Buy",
    price: 1800000,
    rent: 0,
    description: "Extremely affordable independent 1 BHK small house in Narasannapeta. Completely clear titles and approved layout plans. Urgently selling to arrange funds to settle children's business loan.",
    image_url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    owner_name: "G. Apparao Chowdary",
    phone: "+919440123567"
  },
  {
    title: "Studio Room Small House in Vakalapudi",
    location: "Vakalapudi",
    type: "Small House",
    listing_type: "Rent",
    price: 0,
    rent: 4200,
    description: "Single room house with attached bathroom and pantry kitchen. Ideal for working bachelors or industrial workers. Located in a safe family layout in Vakalapudi. Immediate occupancy.",
    image_url: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=800&q=80",
    owner_name: "Y. Rama Rao",
    phone: "+919618123456"
  },
  {
    title: "Prime Location 3 BHK Apartment in Gandhinagar",
    location: "Gandhinagar",
    type: "Apartment",
    listing_type: "Buy",
    price: 7500000,
    rent: 0,
    description: "Premium builder floor apartment in prime residential Gandhinagar area. Very close to local markets, temples, and leading hospitals. Multi-layer security, continuous sweet drinking water, and private storage room.",
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    owner_name: "B. Satya Murthy Raju",
    phone: "+919866456781"
  },
  {
    title: "Spacious 3 BHK Flat in Venkat Nagar",
    location: "Venkat Nagar",
    type: "Apartment",
    listing_type: "Rent",
    price: 0,
    rent: 22000,
    description: "High-density elite residential layout 3 BHK apartment for rent in Venkat Nagar. Deluxe furnishings, geysers in all toilets, modular wardrobes, and split A/C wiring in place. Looking for corporate employee families.",
    image_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    owner_name: "Dr. K. S. Reddy",
    phone: "+919441122334"
  },
  {
    title: "Lovely 2 BHK House in Peddapuram Road",
    location: "Peddapuram Road",
    type: "Individual House",
    listing_type: "Buy",
    price: 3800000,
    rent: 0,
    description: "Independent 2 BHK house located on Peddapuram Road. Just a few minutes walk from Aditya Educational Institutions. Highly suitable for staff or investment-minded individuals who want stable student rents. Spacious overhead water tank.",
    image_url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
    owner_name: "Ch. Venkata Rao",
    phone: "+918978123456"
  }
];
